#!/bin/bash
# make_docx.sh -- build PAPER.docx from PAPER.md for editing in Word.
#
# Strips the repo-facing front matter (draft status table, the "reproduce with"
# line) and moves reproduction detail to an appendix, so the Word file reads as a
# paper rather than as a working file. Re-run after editing PAPER.md; edits made
# in Word do NOT flow back, so PAPER.md stays the source of truth until you decide
# to switch over.
set -euo pipefail
cd "$(dirname "$0")"
command -v pandoc >/dev/null || { echo "pandoc not installed: brew install pandoc"; exit 1; }

python3 - <<'PY'
import re
s = open("PAPER.md").read()

# drop the draft-status block and the reproduce line from the body
i = s.index("Full draft, seven sections")
j = s.index("---\n\n# 1. Introduction")
repro = s[i:j]
s = s[:i] + s[j:]

# pull the reproduction detail into an appendix instead of discarding it
cmds = re.search(r"Reproduce Section.*?\n\n", repro, re.S)
appendix = """
---

# Appendix A. Reproduction

Every estimate in this paper is generated by scripts in the project repository,
which share a single panel construction in `entry_panel.py`.

| Section | Script |
|---|---|
| 3.1 to 3.5, and the decomposition in 8.2 | `section3_core.py` |
| 3.6 | `section3_age_gradient.py` |
| 4.1 to 4.4, 4.6 | `section4_controls.py` |
| 4.5 | `section4_rate_confound.py` |
| 5 | `entry_level_decomposition.py`, `adp_cps_reconciliation.py` |
| 6.1 to 6.4 | `section6_measures.py` |
| 6.5 | `section6_fact5.py` |
| 6.6 | `section6_facts_4_6.py` |

The occupation-by-year panel is rebuilt from the IPUMS CPS extract by
`build_cps_panel_bands.py`. Monthly flows and outgoing-rotation earnings come from
`build_cps_flows.py`, which reads a second extract carrying `CPSIDP`, `MISH`,
`EARNWEEK`, `HOURWAGE`, `EARNWT` and `ELIGORG`.
"""
s = s.rstrip("\n") + "\n" + appendix
open("/tmp/_paper_word.md", "w").write(s)
PY

pandoc /tmp/_paper_word.md \
  -o PAPER.docx \
  --from=gfm \
  --resource-path=. \
  --toc --toc-depth=2 \
  --metadata title="Underperformance Without Contraction" \
  --metadata subtitle="Entry-level employment and AI exposure in nationally representative data" \
  --metadata author="Max Stober" \
  --metadata date="$(date +'%B %Y')"

rm -f /tmp/_paper_word.md
echo "wrote PAPER.docx ($(du -h PAPER.docx | cut -f1))"
